=======
@startuml AHT2_PKZ_OneToOne
start

:acessar o site;
:carregar página inicial;
:exibir informações \nbreves sobre os projetos;
:scrollar para baixo;
:exibir as opções \nPKZ Lab e One to One;
:clicar em "Quero conhecer" \nda PKZ Lab ou One to One;

if (Qual empresa foi selecionada?) then (PKZ Lab)
    :redirecionar para a página\nda PKZ Lab;
    :exibir atalhos no header da página;
    if (O usuário clicou em algum atalho?) then (Sim)
        if (Qual atalho foi clicado?) 
        elseif (Sobre)
            :exibir informações mais\n detalhadas sobre o \nprojeto PKZ Lab;
        elseif (Pais e responsáveis)
            :exibir sessão para\n pais e responsáveis;
        elseif (Serviços)
            :exibir os serviços \noferecidos pelo projeto;
        elseif (Localização)
            :exibir localização \ndo projeto PKZ;
        elseif (Contato)
            :sobrepôr a tela atual \ncom uma menor com a \nopção de informar o nome \ne se comunicar pelo Whatsapp;     
        endif 
        :Scrollar para baixo;
        :exibir footer com o \nInstagram da PKZ Lab \ne a localização do projeto;
        :Clicar no botão com \numa seta para \nvoltar ao topo da \npágina caso necessário;
        :Clicar no botão "Portal" \npara voltar para a \npágina inicial (caso desejado);
    
    else (Não)
        :exibir informações mais\n detalhadas sobre o \nprojeto PKZ Lab;
        :Scrollar para baixo;
        :exibir sessão para\n pais e responsáveis;
        :Scrollar para baixo;
        :exibir os serviços \noferecidos pelo projeto;
        :Scrollar para baixo;
        :exibir localização \ndo projeto PKZ;
        :Scrollar para baixo;
        :exibir footer com o \nInstagram da PKZ Lab \ne a localização do projeto;
        :Clicar no botão com \numa seta para \nvoltar ao topo da \npágina caso necessário;
        :Clicar no botão "Portal" \npara voltar para a \npágina inicial (caso desejado);
        endif


else (One to One)
    :redirecionar para a página\nda One to One;
    :exibir informações da\nOne to One;

endif


stop
@enduml

