=======
@startuml AHT2_PKZ_OneToOne
start

:acessar o site;
:carregar página inicial;
:exibir informações \nbreves sobre os projetos;
:scrollar para baixo;
:exibir as opções \nPKZ Lab e One to One;


@enduml

